# Generated by Django 6.0.3 on 2026-03-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='repo_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
