# Generated by Django 6.0.3 on 2026-03-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_stats_repo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='closed_prs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='open_prs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='streak_days',
            field=models.IntegerField(default=0),
        ),
    ]
